CONTIKI_PROJECT = hello-world sensor-test read_battery pwm_sensor hwsensors embarcados1 buttons atividade3
all: $(CONTIKI_PROJECT)

CONTIKI = ../..
CFLAGS += -g
FLAGS += -g
include $(CONTIKI)/Makefile.include
